apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    prometheus: scrape
  name: api
  namespace: default
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
