apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api
    prometheus: scrape
  name: api
  namespace: default
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: api
  type: LoadBalancer
