apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: task
  name: task
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: task
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: task
    spec:
      containers:
        - env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ACCESS_KEY
                  name: local-env
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ENDPOINT
                  name: local-env
            - name: MINIO_PORT
              valueFrom:
                configMapKeyRef:
                  key: MINIO_PORT
                  name: local-env
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: MINIO_SECRET_KEY
                  name: local-env
            - name: MINIO_USE_SSL
              valueFrom:
                configMapKeyRef:
                  key: MINIO_USE_SSL
                  name: local-env
            - name: MONGOMS_ARCH
              valueFrom:
                configMapKeyRef:
                  key: MONGOMS_ARCH
                  name: local-env
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URL
                  name: local-env
            - name: SERVER_TYPE
              value: worker
          image: thumbnail-task
          name: task
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
