apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    prometheus: scrape
  name: api
  namespace: default
spec:
  selector:
    app: api
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.ports.name }}
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.targetPort }}