apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: availability-alerts
  namespace: prometheus
  labels:
    release: prometheus
    role: alert-rules
spec:
  groups:
    - name: api-availability.rules
      rules:
        - alert: ServiceUnavailbility
          expr: |
            (sum(rate(http_requests_non_200_total[5m])) / sum(rate(http_requests_total[5m]))) > 0.10
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High http non-200 request rate detected"
            description: "More than 10% of requests are failing"
        - alert: HighErrorRate
          expr: |
            (sum(rate(http_failed_responses_total[5m])/2) / sum(rate(http_requests_total[5m]))) > 0.05
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High error rate detected"
            description: "More than 5% of requests are failing"
        - alert: TargetUnavailabilityRate
          expr: 100 * (avg_over_time(up{job="api", namespace="default"}[5m])) < 60
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Target availability below 60%"
            description: "Average availability of targets is below 60% over the last 5 minutes"
