# This file defines a Kubernetes Pod that runs a health probe for the API service.
# Just used to generate metrics for the API service.
# Better approach would be to actually make a request to the API service and check the response.
apiVersion: v1
kind: Pod
metadata:
  name: api-health-prober
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 3
  initContainers:
  - name: wait-for-api
    image: curlimages/curl:latest
    command:
      - sh
      - -c
      - |
        echo "Waiting for API to become available..."
        for i in $(seq 1 30); do
          if curl -sf --connect-timeout 2 --max-time 5 http://api:3000/health; then
            echo "API is available!"
            exit 0
          fi
          echo "Attempt $i: API not ready, retrying in 3s..."
          sleep 3
        done
        echo "API not available after 30 attempts. Exiting."
        exit 1
  containers:
    - name: curl-prober
      image: curlimages/curl:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            echo "$(date) - Probing api:3000/health"
            curl -s -o /dev/null -w "%{http_code}\n" http://api:3000/health
            sleep 60
          done