apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    prometheus: scrape
  name: api
  namespace: default
spec:
  selector:
    app: api
  type: {{ .Values.apiService.type }}
  ports:
    - name: {{ .Values.apiService.ports.name }}
      port: {{ .Values.apiService.ports.port }}
      targetPort: {{ .Values.apiService.targetPort }}