apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
          name: db
          ports:
            - containerPort: {{ .Values.db.ports.containerPort }}
              name: mongo
              protocol: {{ .Values.db.ports.protocol }}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
          resources:
            requests:
              memory: {{ .Values.containers.resources.requests.memory }}
              cpu: {{ .Values.containers.resources.requests.cpu }}
            limits:
              memory: {{ .Values.containers.resources.limits.memory }}
              cpu: {{ .Values.containers.resources.limits.cpu }}
      restartPolicy: {{ .Values.db.restartPolicy }}
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
