apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
    - name: "27017"
      port: {{ .Values.dbService.ports.port }}
      targetPort: {{ .Values.dbService.ports.targetPort }}
      protocol: TCP
  selector:
    app: db
