apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: s3
  name: s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: s3
    spec:
      containers:
        - args:
            - server
            - /data
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: {{ .Values.env.MINIO_ACCESS_KEY.key }}
                  name: {{ .Values.env.MINIO_ACCESS_KEY.name }}
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: {{ .Values.env.MINIO_ENDPOINT.key }}
                  name: {{ .Values.env.MINIO_ENDPOINT.name }}
            - name: MINIO_PORT
              valueFrom:
                configMapKeyRef:
                  key: {{ .Values.env.MINIO_PORT.key }}
                  name: {{ .Values.env.MINIO_PORT.name }}
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: {{ .Values.env.MINIO_SECRET_KEY.key }}
                  name: {{ .Values.env.MINIO_SECRET_KEY.name }}
            - name: MINIO_USE_SSL
              valueFrom:
                configMapKeyRef:
                  key: {{ .Values.env.MINIO_USE_SSL.key }}
                  name: {{ .Values.env.MINIO_USE_SSL.name }}
            - name: MONGOMS_ARCH
              valueFrom:
                configMapKeyRef:
                  key: {{ .Values.env.MONGOMS_ARCH.key }}
                  name: {{ .Values.env.MONGOMS_ARCH.name }}
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  key: {{ .Values.env.MONGO_URL.key }}
                  name: {{ .Values.env.MONGO_URL.name }}
          image: {{ .Values.s3.image.repository }}:{{ .Values.s3.image.tag }}
          imagePullPolicy: {{ .Values.s3.image.pullPolicy }}
          name: s3
          ports:
            - containerPort: {{ .Values.s3.ports.containerPort }}
              protocol: {{ .Values.s3.ports.protocol }}
          resources:
            requests:
              memory: {{ .Values.containers.resources.requests.memory }}
              cpu: {{ .Values.containers.resources.requests.cpu }}
            limits:
              memory: {{ .Values.containers.resources.limits.memory }}
              cpu: {{ .Values.containers.resources.limits.cpu }}
      restartPolicy: {{ .Values.s3.restartPolicy }}
