apiVersion: v1
kind: Service
metadata:
  labels:
    app: s3
  name: s3
spec:
  ports:
    - name: "9000"
      port: {{ .Values.s3Service.ports.port }}
      targetPort: {{ .Values.s3Service.ports.targetPort }}
  selector:
    app: s3
