apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task
  name: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      initContainers:
        - name: wait-for-s3
          image: busybox
          command: ['sh', '-c', 'nslookup s3; until nc -z s3 9000; do echo waiting for s3...; sleep 5; done']
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'nslookup db; until nc -z db 27017; do echo waiting for db...; sleep 5; done'] 
      containers:
        - env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ACCESS_KEY
                  name: local-env
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ENDPOINT
                  name: local-env
            - name: MINIO_PORT
              valueFrom:
                configMapKeyRef:
                  key: MINIO_PORT
                  name: local-env
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: MINIO_SECRET_KEY
                  name: local-env
            - name: MINIO_USE_SSL
              valueFrom:
                configMapKeyRef:
                  key: MINIO_USE_SSL
                  name: local-env
            - name: MONGOMS_ARCH
              valueFrom:
                configMapKeyRef:
                  key: MONGOMS_ARCH
                  name: local-env
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URL
                  name: local-env
            - name: SERVER_TYPE
              value: worker
          image: thumbnail-task
          name: task
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always